### ISSUE TITLE
Unsupported log file format. Latest supported version is 14, the log file has version 16.

### ISSUE THREAD

**Issue by cataggar** [fsprojects/FAKE#2748] opened 2023-05-26 03:56 UTC
Same as #2595, but newer. From that thread, it appears there are two workarounds. Add `DisableInternalBinLog = true` as an option to `DotNet.build`:

``` fsi
DotNet.build (fun o ->
                { o with
                    NoLogo = true
                    MSBuildParams = { o.MSBuildParams with DisableInternalBinLog = true }
```

Or request a newer version of https://www.nuget.org/packages/MSBuild.StructuredLogger in `build.fsx`:
``` fsi
#!/usr/bin/env -S dotnet fsi
#r "nuget: Fake.DotNet.Cli"
#r "nuget: Fake.Core.Target"
#r "nuget: MSBuild.StructuredLogger, 2.1.820"
```

I will be trying them out.

**Comment by cataggar** [comment] 2023-05-26 03:58
Thanks @github-actions. I'm a newbie. ;-)

**Comment by cataggar** [comment] 2023-05-26 07:07
This will be fixed by https://github.com/fsprojects/FAKE/pull/2746.

**Comment by cataggar** [comment] 2023-05-30 00:57
To confirm, this workaround works and is the one I used:

``` fsi
#r "nuget: MSBuild.StructuredLogger, 2.1.820"
```

**Comment by gtbuchanan** [comment] 2023-05-31 15:00
Duplicate of #2744

**Closed** 2023-05-31 15:21 UTC

**Comment by JohnDoeKyrgyz** [comment] 2023-07-12 16:53
When can we expect a new NuGet package to be released with this fix?
