### ISSUE TITLE
How can i set build.fsx to pick VS2019 MSBuild toolversion

### ISSUE THREAD

**Issue by ShipraRay** [fsprojects/FAKE#2697] opened 2022-09-06 14:47 UTC
How can i set build.fsx to pick VS2019 MSBuild toolversion

### Repro steps

In my local machine i have VS2019 where the soln.fsx file is building fine(I have set the MSBuild environment path as 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin')

But in Azure Devops pipeline it is failing, i am selecting Agent Specification as windows-2019

### Expected behavior

In my sln.fsx file below line:

Fake.DotNet.MSBuild.run is not picking the current VS2019 MSBuild

### Actual behavior

How can i make the change in soln.fsx file to pick the VS2019 MSBuild ? 
so that in Azure Devops pipeline mu build scripts pass when selecting agent windows-2019
(Before we were using agent specification-vs2017-win2016', when the build was successfull but microsoft have deprecated this agent from 2022 onwards).
Please help!

* Operating system - Windows 10

* Version of FAKE - 5.3.0.0
* (if performance issue) Performance information, links to performance testing scripts

**Comment by yazeedobaid** [comment] 2022-09-08 07:45
Thanks for reporting, so you know the path to MSBuild on the Azure pipeline but the MSBuild task from FAKE is not picking up that path? If that is the case, could you please provide the path you know so that we can debug it more? And as a workaround, can you try one of these options:
1. Try to set the MSBuild tool location from the AppSettings file using a parameter named `MSBuild`
2. Specify the `VisualStudioVersion` environment variable, MSBuild task in FAKE try to use the specific MSBuild version, matching that Visual Studio version.

Also, the paths that FAKE search for are [specified here](https://github.com/fsprojects/FAKE/blob/c0268637810752dec090506d3f85190af1b99637/src/app/Fake.DotNet.MSBuild/MSBuild.fs#L131)

**Comment by ShipraRay** [comment] 2022-09-08 08:21
In my build.fsx file added this to forcibly take VS 2019 version but still it didnot worked:

let toolsVersion = "Current"
 
let setParams defaults =
        { defaults with
            Verbosity = Some(Quiet)
            ToolsVersion = Some(toolsVersion)
            Targets = ["Build"]
            Properties =
                [
                    "Optimize", "True"
                    "DebugSymbols", "True"
                    "Configuration", buildMode
                ]
         }

Need some help to fix the pipeline build issue!

**Comment by yazeedobaid** [comment] 2022-09-08 08:41
Could you please share a complete build script that has the issue, the error message you get from Azure Pipeline, and the path to MSBuild in Azure Pipeline that FAKE is failing to find?

**Comment by yazeedobaid** [comment] 2022-10-21 14:20
Closing this issue since it is a duplicate of #2703

**Closed by yazeedobaid** 2022-10-21 14:20 UTC
