### ISSUE TITLE
Missing github release for 6.1.0

### ISSUE THREAD

**Issue by NogginBops** [fsprojects/FAKE#2800] opened 2024-08-06 21:26 UTC
### Description

The 6.1.0 nuget package has been released without a matching GitHub release tag.

This should probably be fixed, and even if the 6.1.0 nuget package is accidental a matching tag should probably be established anyway.

**Comment by xperiandri** [comment] 2024-08-06 22:05
@NogginBops I know
Pipeline crashes so it had not completed altogether.
I thought `ignore_push` https://github.com/fsprojects/FAKE/blob/b5856057257c5a5dab38cc0f7875f58442af513e/build.fsx#L480 is `--skip-duplicate` in `dotnet nuget push`
But it did not work the same.

So now I have 2 release pipelines crashed:
1. Pushed NuGet but stop on docs publishing
2. Did not skip pushing a duplicate

If you can help I'll appreciate

**Comment by xperiandri** [comment] 2024-08-06 22:08
The other question is will the first release pipeline pick up the changes pushed to main if rerun?

**Comment by NogginBops** [comment] 2024-08-06 22:13
I'm not very familiar with the github actions setup in this repo, my guess is that the best course of action is probably to manually add the GitHub release to match the nuget release. Then fixing/understanding the action and the failure can be understood and a new potentially fixed nuget package can be released (and the old nuget package can be unlisted or deprecated if necessary.)

I could potentially look into the GitHub actions tomorrow and see if I can make sense of anything enough to be helpful.

**Comment by xperiandri** [comment] 2024-08-06 22:15
No new package needs to be release. Just fix skipping pushing the same version of the package

**Comment by Numpsy** [comment] 2024-08-20 17:59
Is it worth trying to publish the docs with a specific github action rather than doing it manually in the fsx script? 
e.g. https://github.com/fsprojects/fantomas/blob/a4788cbdf856ae6f47b6032f7cb8ecb506ad7733/.github/workflows/main.yml#L39

**Comment by xperiandri** [comment] 2024-08-20 22:43
I would prefer fixing the pipeline

**Comment by Numpsy** [comment] 2024-08-21 12:21
Not sure if this is it, but it looks like the Release.Id property was changed from an int to a long in https://github.com/octokit/octokit.net/pull/2941

**Comment by xperiandri** [comment] 2024-08-21 12:56
Approved PR, waiting for build to complete

**Comment by Numpsy** [comment] 2024-08-21 19:12
And now it seems to have failed because the previous run successfully pushed a build to Chocolately, and you can't do that twice for the same version :-(

**Comment by xperiandri** [comment] 2024-08-21 23:13
Skip needed again 😄

**Comment by Numpsy** [comment] 2024-08-22 10:59
I don't an 'ignore duplicates' type option in the ```choco push``` docs at https://docs.chocolatey.org/en-us/create/commands/push/ (I've never pushed anything into chocolately myself)

**Comment by xperiandri** [comment] 2024-08-22 11:02
For NuGet it just wraps code in try-with. And if skip flag, then ignore exception

**Comment by xperiandri** [comment] 2024-08-24 13:12
I hope it is the last piece to fix release pipeline

**Comment by Numpsy** [comment] 2024-08-25 09:04
I can try something like https://github.com/Numpsy/FAKE/commit/07ac9879a6b6354b68bc2a2064f8f17cbae74e5b which might avoid the immediate failure, but the choco docs only list processes exit codes of 0/1 so I don't know how to determine if the error was a conflict or not other than trying to look at the ```An error has occurred. This package version already exists on the repository and cannot be modified.``` console output (which I don't think is directly available at this point in the script

**Comment by Numpsy** [comment] 2024-08-28 17:48
> I hope it is the last piece to fix release pipeline

Looks like the latest attempt has failed because it tried to create a 6.1.0 git tag, and one already exists :-(

**Comment by xperiandri** [comment] 2024-08-29 00:01
Something new now

**Comment by Numpsy** [comment] 2024-08-29 07:56
Hmm, that's back to what #2808 was intended to fix (The release id is a long instead of Int32 now, and something seems to be getting confused somewhere)

**Comment by Numpsy** [comment] 2024-08-29 08:21
Could it be that build.fsx is downloading the latest version of Octokit (13), and calling it via the old release of Fake.Api.GitHub rather than the version currently being built (and then the mismatch upsets things)?

**Comment by Numpsy** [comment] 2024-08-29 21:15
Hurrah, finally a successful release build, and the 6.1.0 release is listed now

**Comment by xperiandri** [comment] 2024-08-31 13:54
Yahoo! 🎉🎉🎉
@Numpsy @Thorium do you want 6.1.1 release with what's already merged?

**Comment by Thorium** [comment] 2024-08-31 21:17
I would prefer 6.1.1 asap because it would unblock some net8 migration issues. I don't really care "should we include one more PR or not", as the currently merged PRs already solve the issues (as I tested merged version directly locally).

**Comment by Numpsy** [comment] 2024-08-31 21:28
Might be useful to do a quick release to fix #2803 if people are trying to use it with the .NET 9 previews and that helps to get that tested

**Comment by xperiandri** [comment] 2024-09-01 15:48
Released

**Closed by xperiandri** 2024-09-01 15:48 UTC
